AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: mePay charge card api

Resources:
  ChargePayment:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Events:
        ChargeCard:
          Type: Api
          Properties:
            Path: /chargecard
            Method: post
            Cors: true